{% set name = "pythonvirgotools" %}
{% set version = "5.1.2" %}

package:
   name: "{{ name }}"
   version: "{{ version }}"

source:
   url: http://software.igwn.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
   sha256: f4a43ea6325c075a1d0992e1e8808d956278e8014107f854991206070476bd47

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - pip
    - python >=2.7
    - setuptools
  run:
    - python >=2.7
    - pyfd
    - pycm
    - future
    - numpy
    - pytz

test:
  imports:
    - virgotools

about:
  home: "https://git.ligo.org/virgo/virgoapp/PythonVirgoTools"
  license: "GPL-2.0-or-later"
  license_family: "GPL"
  license_file: "LICENSE"
  summary:
    PythonVirgoTools is a collection of Python functions for interacting 
    with the software, hardware and data of the Virgo Interferometer. 
    These functions were mainly written for daily use in the control room, 
    but some of these might also be useful for e.g. DetChar work.

extra:
  recipe-maintainers:
      - rhyspoulton
      - fcarbogn 
