{% set name = "pythonvirgotools" %}
{% set version = "5.1.3" %}

package:
   name: "{{ name }}"
   version: "{{ version }}"

source:
   url: http://software.igwn.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
   sha256: 2b4726ea02264a38ae3dd307eda6b49fa80f626ceeec76ebe9b8e0503115e2d7

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - pip
    - python >=2.7
    - setuptools
  run:
    - python >=2.7
    - pyfd
    - pycm
    - future
    - numpy
    - pytz
    - tzlocal <=2.1

test:
  imports:
    - virgotools

about:
  home: "https://git.ligo.org/virgo/virgoapp/PythonVirgoTools"
  license: "GPL-2.0-or-later"
  license_family: "GPL"
  license_file: "LICENSE"
  summary:
    PythonVirgoTools is a collection of Python functions for interacting 
    with the software, hardware and data of the Virgo Interferometer. 
    These functions were mainly written for daily use in the control room, 
    but some of these might also be useful for e.g. DetChar work.

extra:
  recipe-maintainers:
      - rhyspoulton
      - fcarbogn 
